/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as BurnWormContractJson } from "../burnworm/BurnWorm.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace BurnWormTypes {
  export type Fields = {
    ngu: HexString;
    ngufee: bigint;
    alphfee: bigint;
    owner: Address;
    alphbalance: bigint;
    ngubalance: bigint;
  };

  export type State = ContractState<Fields>;

  export type BurnEvent = ContractEvent<{
    token: HexString;
    amount: bigint;
    who: Address;
    when: bigint;
  }>;
  export type DestroyEvent = ContractEvent<{ from: Address }>;

  export interface CallMethodTable {
    getNgu: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNguFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAlphFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<BurnWormInstance, BurnWormTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as BurnWormTypes.Fields;
  }

  eventIndex = { Burn: 0, Destroy: 1 };
  consts = { Error: { InvalidCaller: BigInt(0) } };

  at(address: string): BurnWormInstance {
    return new BurnWormInstance(address);
  }

  tests = {
    getNgu: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getNgu", params);
    },
    getNguFee: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getNguFee", params);
    },
    getAlphFee: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getAlphFee", params);
    },
    burntokenalph: async (
      params: TestContractParams<
        BurnWormTypes.Fields,
        { id: HexString; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "burntokenalph", params);
    },
    burntokenngu: async (
      params: TestContractParams<
        BurnWormTypes.Fields,
        { id: HexString; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "burntokenngu", params);
    },
    withdrawalph: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdrawalph", params);
    },
    withdrawngu: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdrawngu", params);
    },
    destroy: async (
      params: Omit<TestContractParams<BurnWormTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const BurnWorm = new Factory(
  Contract.fromJson(
    BurnWormContractJson,
    "",
    "2b43b79e25c2873c5bd8d635f64cc6d4da3ca2bf75063e0e2c38078892d29570"
  )
);

// Use this class to interact with the blockchain
export class BurnWormInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BurnWormTypes.State> {
    return fetchContractState(BurnWorm, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<BurnWormTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      BurnWorm.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribeDestroyEvent(
    options: EventSubscribeOptions<BurnWormTypes.DestroyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      BurnWorm.contract,
      this,
      options,
      "Destroy",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      BurnWormTypes.BurnEvent | BurnWormTypes.DestroyEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(BurnWorm.contract, this, options, fromCount);
  }

  methods = {
    getNgu: async (
      params?: BurnWormTypes.CallMethodParams<"getNgu">
    ): Promise<BurnWormTypes.CallMethodResult<"getNgu">> => {
      return callMethod(
        BurnWorm,
        this,
        "getNgu",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNguFee: async (
      params?: BurnWormTypes.CallMethodParams<"getNguFee">
    ): Promise<BurnWormTypes.CallMethodResult<"getNguFee">> => {
      return callMethod(
        BurnWorm,
        this,
        "getNguFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAlphFee: async (
      params?: BurnWormTypes.CallMethodParams<"getAlphFee">
    ): Promise<BurnWormTypes.CallMethodResult<"getAlphFee">> => {
      return callMethod(
        BurnWorm,
        this,
        "getAlphFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends BurnWormTypes.MultiCallParams>(
    calls: Calls
  ): Promise<BurnWormTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      BurnWorm,
      this,
      calls,
      getContractByCodeHash
    )) as BurnWormTypes.MultiCallResults<Calls>;
  }
}
