/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as BurnTokenContractJson } from "../burn/BurnToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace BurnTokenTypes {
  export type Fields = {
    tokensburned: bigint;
    token: HexString;
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export type BurnEvent = ContractEvent<{
    from: Address;
    amount: bigint;
    when: bigint;
    totalburned: bigint;
  }>;
  export type DestroyEvent = ContractEvent<{ from: Address }>;

  export interface CallMethodTable {
    getToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    burntoken: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    destroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    getToken: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    burntoken: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    destroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  BurnTokenInstance,
  BurnTokenTypes.Fields
> {
  encodeFields(fields: BurnTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as BurnTokenTypes.Fields;
  }

  eventIndex = { Burn: 0, Destroy: 1 };
  consts = { Error: { InvalidCaller: BigInt(0) } };

  at(address: string): BurnTokenInstance {
    return new BurnTokenInstance(address);
  }

  tests = {
    getToken: async (
      params: Omit<
        TestContractParamsWithoutMaps<BurnTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getToken", params, getContractByCodeHash);
    },
    burntoken: async (
      params: TestContractParamsWithoutMaps<
        BurnTokenTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burntoken", params, getContractByCodeHash);
    },
    destroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<BurnTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroy", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const BurnToken = new Factory(
  Contract.fromJson(
    BurnTokenContractJson,
    "",
    "1d435c370e0a07477be805acfe7546cfab007f024808319deaf5dff9b4e61de4",
    []
  )
);

// Use this class to interact with the blockchain
export class BurnTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BurnTokenTypes.State> {
    return fetchContractState(BurnToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<BurnTokenTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      BurnToken.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribeDestroyEvent(
    options: EventSubscribeOptions<BurnTokenTypes.DestroyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      BurnToken.contract,
      this,
      options,
      "Destroy",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      BurnTokenTypes.BurnEvent | BurnTokenTypes.DestroyEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      BurnToken.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getToken: async (
      params?: BurnTokenTypes.CallMethodParams<"getToken">
    ): Promise<BurnTokenTypes.CallMethodResult<"getToken">> => {
      return callMethod(
        BurnToken,
        this,
        "getToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    burntoken: async (
      params: BurnTokenTypes.CallMethodParams<"burntoken">
    ): Promise<BurnTokenTypes.CallMethodResult<"burntoken">> => {
      return callMethod(
        BurnToken,
        this,
        "burntoken",
        params,
        getContractByCodeHash
      );
    },
    destroy: async (
      params?: BurnTokenTypes.CallMethodParams<"destroy">
    ): Promise<BurnTokenTypes.CallMethodResult<"destroy">> => {
      return callMethod(
        BurnToken,
        this,
        "destroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    getToken: async (
      params: BurnTokenTypes.SignExecuteMethodParams<"getToken">
    ): Promise<BurnTokenTypes.SignExecuteMethodResult<"getToken">> => {
      return signExecuteMethod(BurnToken, this, "getToken", params);
    },
    burntoken: async (
      params: BurnTokenTypes.SignExecuteMethodParams<"burntoken">
    ): Promise<BurnTokenTypes.SignExecuteMethodResult<"burntoken">> => {
      return signExecuteMethod(BurnToken, this, "burntoken", params);
    },
    destroy: async (
      params: BurnTokenTypes.SignExecuteMethodParams<"destroy">
    ): Promise<BurnTokenTypes.SignExecuteMethodResult<"destroy">> => {
      return signExecuteMethod(BurnToken, this, "destroy", params);
    },
  };

  async multicall<Calls extends BurnTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<BurnTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      BurnToken,
      this,
      calls,
      getContractByCodeHash
    )) as BurnTokenTypes.MultiCallResults<Calls>;
  }
}
