/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as CreateswapContractJson } from "../swaps/Createswap.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace CreateswapTypes {
  export type Fields = {
    owner: Address;
    contract: HexString;
    paca: HexString;
    ngu: HexString;
    pacafee: bigint;
    alphfee: bigint;
    ngufee: bigint;
  };

  export type State = ContractState<Fields>;

  export type SwapEvent = ContractEvent<{
    tokeno: HexString;
    amto: bigint;
    tokenw: HexString;
    amtw: bigint;
    contract: HexString;
  }>;
  export type LendEvent = ContractEvent<{
    tokeno: HexString;
    amto: bigint;
    tokenw: HexString;
    amtw: bigint;
    contract: HexString;
  }>;
  export type DestroyEvent = ContractEvent<{ who: Address }>;

  export interface CallMethodTable {
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getPacaFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAlphFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPacaToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNguToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNguFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  CreateswapInstance,
  CreateswapTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as CreateswapTypes.Fields;
  }

  eventIndex = { Swap: 0, Lend: 1, Destroy: 2 };
  consts = { ErrorCodes: { InvalidCaller: BigInt(1) } };

  at(address: string): CreateswapInstance {
    return new CreateswapInstance(address);
  }

  tests = {
    getTokenId: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenId", params);
    },
    getPacaFee: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getPacaFee", params);
    },
    getAlphFee: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getAlphFee", params);
    },
    getPacaToken: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getPacaToken", params);
    },
    getNguToken: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getNguToken", params);
    },
    getNguFee: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getNguFee", params);
    },
    createswappaca: async (
      params: TestContractParams<
        CreateswapTypes.Fields,
        {
          tokenOffered: HexString;
          tokenOfferedAmt: bigint;
          tokenWanted: HexString;
          tokenWantedAmt: bigint;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createswappaca", params);
    },
    createswapngu: async (
      params: TestContractParams<
        CreateswapTypes.Fields,
        {
          tokenOffered: HexString;
          tokenOfferedAmt: bigint;
          tokenWanted: HexString;
          tokenWantedAmt: bigint;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createswapngu", params);
    },
    createswapalph: async (
      params: TestContractParams<
        CreateswapTypes.Fields,
        {
          tokenOffered: HexString;
          tokenOfferedAmt: bigint;
          tokenWanted: HexString;
          tokenWantedAmt: bigint;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createswapalph", params);
    },
    feepaca: async (
      params: TestContractParams<CreateswapTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "feepaca", params);
    },
    feealph: async (
      params: TestContractParams<CreateswapTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "feealph", params);
    },
    feengu: async (
      params: TestContractParams<CreateswapTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "feengu", params);
    },
    destroytokenswap: async (
      params: Omit<
        TestContractParams<CreateswapTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroytokenswap", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Createswap = new Factory(
  Contract.fromJson(
    CreateswapContractJson,
    "",
    "ee0d422da610ac195fa99322c2f527d854564158ca5f95ff42118600653fa585"
  )
);

// Use this class to interact with the blockchain
export class CreateswapInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CreateswapTypes.State> {
    return fetchContractState(Createswap, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeSwapEvent(
    options: EventSubscribeOptions<CreateswapTypes.SwapEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Createswap.contract,
      this,
      options,
      "Swap",
      fromCount
    );
  }

  subscribeLendEvent(
    options: EventSubscribeOptions<CreateswapTypes.LendEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Createswap.contract,
      this,
      options,
      "Lend",
      fromCount
    );
  }

  subscribeDestroyEvent(
    options: EventSubscribeOptions<CreateswapTypes.DestroyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Createswap.contract,
      this,
      options,
      "Destroy",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | CreateswapTypes.SwapEvent
      | CreateswapTypes.LendEvent
      | CreateswapTypes.DestroyEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      Createswap.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getTokenId: async (
      params?: CreateswapTypes.CallMethodParams<"getTokenId">
    ): Promise<CreateswapTypes.CallMethodResult<"getTokenId">> => {
      return callMethod(
        Createswap,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPacaFee: async (
      params?: CreateswapTypes.CallMethodParams<"getPacaFee">
    ): Promise<CreateswapTypes.CallMethodResult<"getPacaFee">> => {
      return callMethod(
        Createswap,
        this,
        "getPacaFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAlphFee: async (
      params?: CreateswapTypes.CallMethodParams<"getAlphFee">
    ): Promise<CreateswapTypes.CallMethodResult<"getAlphFee">> => {
      return callMethod(
        Createswap,
        this,
        "getAlphFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPacaToken: async (
      params?: CreateswapTypes.CallMethodParams<"getPacaToken">
    ): Promise<CreateswapTypes.CallMethodResult<"getPacaToken">> => {
      return callMethod(
        Createswap,
        this,
        "getPacaToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNguToken: async (
      params?: CreateswapTypes.CallMethodParams<"getNguToken">
    ): Promise<CreateswapTypes.CallMethodResult<"getNguToken">> => {
      return callMethod(
        Createswap,
        this,
        "getNguToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNguFee: async (
      params?: CreateswapTypes.CallMethodParams<"getNguFee">
    ): Promise<CreateswapTypes.CallMethodResult<"getNguFee">> => {
      return callMethod(
        Createswap,
        this,
        "getNguFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends CreateswapTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CreateswapTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Createswap,
      this,
      calls,
      getContractByCodeHash
    )) as CreateswapTypes.MultiCallResults<Calls>;
  }
}
