/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as BuildtokenScriptJson } from "../createtoken/Buildtoken.ral.json";
import { default as BurnScriptJson } from "../burn/Burn.ral.json";
import { default as BurnWangScriptJson } from "../burnwang/BurnWang.ral.json";
import { default as BuyvirlScriptJson } from "../ico/Buyvirl.ral.json";
import { default as DepositScriptJson } from "../subscribe/Deposit.ral.json";
import { default as DestroyScriptJson } from "../faucet/Destroy.ral.json";
import { default as DestroyWormScriptJson } from "../burnworm/DestroyWorm.ral.json";
import { default as DestroyburnScriptJson } from "../burn/Destroyburn.ral.json";
import { default as DestroyburnwangScriptJson } from "../burnwang/Destroyburnwang.ral.json";
import { default as DestroytokenScriptJson } from "../createtoken/Destroytoken.ral.json";
import { default as EditfeeScriptJson } from "../scripts/Editfee.ral.json";
import { default as GettokenScriptJson } from "../scripts/Gettoken.ral.json";
import { default as ReedeemalphScriptJson } from "../ico/Reedeemalph.ral.json";
import { default as SellvirlScriptJson } from "../ico/Sellvirl.ral.json";
import { default as SendoutScriptJson } from "../faucet/Sendout.ral.json";
import { default as SubdestroyScriptJson } from "../subscribe/Subdestroy.ral.json";
import { default as TopupScriptJson } from "../faucet/Topup.ral.json";
import { default as UpdatedevfeeScriptJson } from "../subscribe/Updatedevfee.ral.json";
import { default as WithdrawdevScriptJson } from "../subscribe/Withdrawdev.ral.json";
import { default as WithdrawlassetsScriptJson } from "../scripts/Withdrawlassets.ral.json";
import { default as WithdrawplatformScriptJson } from "../subscribe/Withdrawplatform.ral.json";
import { default as WormEatAlphScriptJson } from "../burnworm/WormEatAlph.ral.json";
import { default as WormEatNguScriptJson } from "../burnworm/WormEatNgu.ral.json";
import { default as WormWithdrawAlphScriptJson } from "../burnworm/WormWithdrawAlph.ral.json";
import { default as WormWithdrawNguScriptJson } from "../burnworm/WormWithdrawNgu.ral.json";

export const Buildtoken = new ExecutableScript<{
  contract: HexString;
  symbol: HexString;
  name: HexString;
  decimals: bigint;
  tokenTotal: bigint;
}>(Script.fromJson(BuildtokenScriptJson, "", []));

export const Burn = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(BurnScriptJson, "", []));

export const BurnWang = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(BurnWangScriptJson, "", []));

export const Buyvirl = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(BuyvirlScriptJson, "", []));

export const Deposit = new ExecutableScript<{
  contract: HexString;
  discordname: HexString;
}>(Script.fromJson(DepositScriptJson, "", []));

export const Destroy = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DestroyScriptJson, "", [])
);

export const DestroyWorm = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DestroyWormScriptJson, "", [])
);

export const Destroyburn = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DestroyburnScriptJson, "", [])
);

export const Destroyburnwang = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DestroyburnwangScriptJson, "", [])
);

export const Destroytoken = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DestroytokenScriptJson, "", [])
);

export const Editfee = new ExecutableScript<{
  contract: HexString;
  edit: bigint;
}>(Script.fromJson(EditfeeScriptJson, "", []));

export const Gettoken = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(GettokenScriptJson, "", []));

export const Reedeemalph = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(ReedeemalphScriptJson, "", []));

export const Sellvirl = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(SellvirlScriptJson, "", []));

export const Sendout = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(SendoutScriptJson, "", []));

export const Subdestroy = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(SubdestroyScriptJson, "", [])
);

export const Topup = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
}>(Script.fromJson(TopupScriptJson, "", []));

export const Updatedevfee = new ExecutableScript<{
  contract: HexString;
  newfee: bigint;
}>(Script.fromJson(UpdatedevfeeScriptJson, "", []));

export const Withdrawdev = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(WithdrawdevScriptJson, "", [])
);

export const Withdrawlassets = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(WithdrawlassetsScriptJson, "", [])
);

export const Withdrawplatform = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(WithdrawplatformScriptJson, "", [])
);

export const WormEatAlph = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
  id: HexString;
}>(Script.fromJson(WormEatAlphScriptJson, "", []));

export const WormEatNgu = new ExecutableScript<{
  contract: HexString;
  amount: bigint;
  id: HexString;
}>(Script.fromJson(WormEatNguScriptJson, "", []));

export const WormWithdrawAlph = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(WormWithdrawAlphScriptJson, "", [])
);

export const WormWithdrawNgu = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(WormWithdrawNguScriptJson, "", [])
);
