/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as ViralContractJson } from "../ico/Viral.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ViralTypes {
  export type Fields = {
    tokenId: HexString;
    balance: bigint;
    alphbalance: bigint;
    pricevirl: bigint;
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export type SellEvent = ContractEvent<{
    from: Address;
    amount: bigint;
    balvirl: bigint;
  }>;
  export type BuyEvent = ContractEvent<{
    to: Address;
    amount: bigint;
    balalph: bigint;
    balvirl: bigint;
  }>;
  export type WithdrawAlphEvent = ContractEvent<{ to: Address }>;

  export interface CallMethodTable {
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getBalance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    tokenPrice: {
      params: CallContractParams<{ price: bigint; amount: bigint }>;
      result: CallContractResult<bigint>;
    };
    getPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAlphBalance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<ViralInstance, ViralTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as ViralTypes.Fields;
  }

  eventIndex = { Sell: 0, Buy: 1, WithdrawAlph: 2 };
  consts = { ErrorCodes: { InvalidCaller: BigInt(3) } };

  at(address: string): ViralInstance {
    return new ViralInstance(address);
  }

  tests = {
    getTokenId: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenId", params);
    },
    getBalance: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getBalance", params);
    },
    getSymbol: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    tokenPrice: async (
      params: TestContractParams<
        ViralTypes.Fields,
        { price: bigint; amount: bigint }
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "tokenPrice", params);
    },
    getPrice: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getPrice", params);
    },
    getAlphBalance: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getAlphBalance", params);
    },
    buyvirl: async (
      params: TestContractParams<ViralTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "buyvirl", params);
    },
    sell: async (
      params: TestContractParams<ViralTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "sell", params);
    },
    removealph: async (
      params: Omit<TestContractParams<ViralTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "removealph", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Viral = new Factory(
  Contract.fromJson(
    ViralContractJson,
    "",
    "d87d6c74c21a7bec6cba00e9a0388ca81c5a71518b8efb77f43b5160cfdd4456"
  )
);

// Use this class to interact with the blockchain
export class ViralInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ViralTypes.State> {
    return fetchContractState(Viral, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeSellEvent(
    options: EventSubscribeOptions<ViralTypes.SellEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Viral.contract,
      this,
      options,
      "Sell",
      fromCount
    );
  }

  subscribeBuyEvent(
    options: EventSubscribeOptions<ViralTypes.BuyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Viral.contract,
      this,
      options,
      "Buy",
      fromCount
    );
  }

  subscribeWithdrawAlphEvent(
    options: EventSubscribeOptions<ViralTypes.WithdrawAlphEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Viral.contract,
      this,
      options,
      "WithdrawAlph",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      ViralTypes.SellEvent | ViralTypes.BuyEvent | ViralTypes.WithdrawAlphEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Viral.contract, this, options, fromCount);
  }

  methods = {
    getTokenId: async (
      params?: ViralTypes.CallMethodParams<"getTokenId">
    ): Promise<ViralTypes.CallMethodResult<"getTokenId">> => {
      return callMethod(
        Viral,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getBalance: async (
      params?: ViralTypes.CallMethodParams<"getBalance">
    ): Promise<ViralTypes.CallMethodResult<"getBalance">> => {
      return callMethod(
        Viral,
        this,
        "getBalance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSymbol: async (
      params?: ViralTypes.CallMethodParams<"getSymbol">
    ): Promise<ViralTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        Viral,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ViralTypes.CallMethodParams<"getName">
    ): Promise<ViralTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Viral,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    tokenPrice: async (
      params: ViralTypes.CallMethodParams<"tokenPrice">
    ): Promise<ViralTypes.CallMethodResult<"tokenPrice">> => {
      return callMethod(
        Viral,
        this,
        "tokenPrice",
        params,
        getContractByCodeHash
      );
    },
    getPrice: async (
      params?: ViralTypes.CallMethodParams<"getPrice">
    ): Promise<ViralTypes.CallMethodResult<"getPrice">> => {
      return callMethod(
        Viral,
        this,
        "getPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAlphBalance: async (
      params?: ViralTypes.CallMethodParams<"getAlphBalance">
    ): Promise<ViralTypes.CallMethodResult<"getAlphBalance">> => {
      return callMethod(
        Viral,
        this,
        "getAlphBalance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends ViralTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ViralTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Viral,
      this,
      calls,
      getContractByCodeHash
    )) as ViralTypes.MultiCallResults<Calls>;
  }
}
